# Generated by Django 5.0.6 on 2024-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='github_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_streak', models.URLField(max_length=500)),
                ('github_contribution', models.URLField(max_length=500)),
                ('github_language_used', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='leetcode_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leetcode_profile', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='projectstats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='project_image/')),
                ('project_title', models.CharField(max_length=100)),
                ('contribution', models.CharField(choices=[('OP', 'Open Source'), ('PP', 'Personal Project')], default='PP', max_length=2)),
                ('project_description', models.TextField(max_length=800)),
                ('source_code', models.URLField(max_length=500)),
                ('deployed_link', models.URLField(max_length=500)),
            ],
        ),
    ]
