# Generated by Django 5.0.6 on 2024-07-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='soft_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_image', models.ImageField(upload_to='skill_image/')),
                ('skill_name', models.CharField(max_length=100)),
            ],
        ),
    ]
