# Generated by Django 5.0.6 on 2024-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_soft_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstats',
            name='tech_stack',
            field=models.TextField(default='python', max_length=500),
        ),
    ]
