# Generated by Django 5.0.6 on 2024-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projectstats_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstats',
            name='deployed_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
